### ISSUE TITLE
Hexpansion Example

### ISSUE THREAD

**Issue by egelmex** [emfcamp/badge-2024-hardware#5]
Would it be useful in the user notes layer for the PCB to include a line showing the cut off between the area covered by the top plate and the area outside this?

**Comment by kliment** [comment]
Possibly - though it's exactly the centerline between the two hexagon points.

**Comment by egelmex** [comment]
Ah thanks, wasn't clear from this picture [Hexpansion](https://tildagon.badge.emfcamp.org/technical-reference/hexpansions/). Are there any technical drawing of the dimension etc that I have failed to find to work from?

**Comment by kliment** [comment]
No, we're literally writing docs right this second. Have a dimensioned drawing to start with:

https://pads.orga.emfcamp.org/uploads/b456ffb9-f5bf-4387-b8ec-fd9796ad957b.png

**Comment by egelmex** [comment]
amazing thank you.

**Comment by kliment** [comment]
Relevant information is now at https://tildagon.badge.emfcamp.org/technical-reference/hexpansions/

**Comment by kliment** [comment]
The template is also now updated.

**Comment by egelmex** [comment]
Thanks Kilment, the documenation looks great.
